# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 8453
  start_block: 0
  contracts:
  - name: SocialDexDeployer
    address:
    - 0x250c9FB2b411B48273f69879007803790A6AeA47
    handler: src/EventHandlers.ts
    events:
    - event: TokenCreated(address tokenAddress, uint256 lpNftId, address deployer, string name, string symbol, uint256 supply, uint256 _supply, address lockerAddress)
  - name: Clanker
    address:
    - 0x9B84fcE5Dcd9a38d2D01d5D72373F6b6b067c3e1
    handler: src/EventHandlers.ts
    events:
    - event: TokenCreated(address tokenAddress, uint256 lpNftId, address deployer, uint256 fid, string name, string symbol, uint256 supply, address lockerAddress, string castHash)
rollback_on_reorg: false
